config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, controllers: { registrations: 'users/registrations'}
  root "short_links#home"
  
  # PWA routes
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  resources :short_links do
    resource :analytics, only: [:show]
  end
  
  post 'qr_download', to: 'short_links#qr_download', as: :qr_download
  
  get '/about', to: 'static_pages#about', as: 'about'
  get '/terms', to: 'static_pages#terms', as: 'terms_of_service'
  get '/profile', to: 'users#profile', as: 'user_profile'
  post "/", to: 'short_links#home', as: 'short_link_home' 
  get '/:short_link', to: 'short_links#home', as: 'short_link_redirect'
  

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
        # :reconfirmable

  has_many :short_links, dependent: :destroy
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]
  
  def create
    super do |resource|
      if resource.persisted?
        #success

        Rails.logger.info "New signup: user id #{resource.id} registered with #{resource.email} at #{Time.current}"
      else
        #failure
 
        Rails.logger.warn "Failed signup: #{Time.current} - Errors: #{resource.errors.full_messages.join(', ')}"
      end
    end
  end
  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [:profile]
  


  def profile
    @user = current_user
    @short_links = @user.short_links
  end
end

app/views/users/profile.html.erb
<main>
  <div class="container">
    <div class="profile-header">
      <h2>Welcome, <%= @user.email %></h2>
      <p>You have <%= @short_links.count %> shortened links</p>
    </div>

    <% if @short_links.any? %>
            <% @short_links.each do |link| %>
              <div class="short-link-item">
                <div class="short-and-orig-links">
                  <div class="original-link">
                    <a href="<%= link.original_link %>" target="_blank" rel="noopener noreferrer">
                      <%= truncate(link.original_link, length: 50) %>
                    </a>
                  </div>
                  <div class="short-link">
                    <%= link_to short_link_redirect_path(link.short_link) do %>
                      https://yintii.com/<%= link.short_link %>
                    <% end %>     
                  </div>
                </div>
                <button class="short-link-btn" data-link="https://yintii.com/<%= link.short_link %>">
                  <i class="fa fa-qrcode" aria-hidden="true"></i>
                </button>
                <%= link_to short_link_analytics_path(link) do %>
                  <button class="short-link-btn">
                    <i class="fa-solid fa-chart-line"></i>
                  </button>
                <% end %>
                <button class="short-link-btn copy-to-clipboard" data-link="https://yintii.com/<%= link.short_link %>">
                  <i class="fa-solid fa-copy"></i>
                </button>
              </div>
            <% end %>
          </tbody>
        </table>
      </div>
    <% else %>
      <div class="empty-state">
        <p>You haven't created any shortened links yet.</p>
        <p><%= link_to "Create one now", root_path, class: "shared-link" %></p>
      </div>
    <% end %>
  </div>

  <script>
    document.querySelectorAll('.copy-to-clipboard').forEach(button => {
      button.addEventListener('click', function() {
        const link = this.getAttribute('data-link');
        navigator.clipboard.writeText(link).then(() => {
          const originalHTML = this.innerHTML;
          this.innerHTML = 'Copied!';
          setTimeout(() => {
            this.innerHTML = originalHTML;
          }, 2000);
        });
      });
    });
  </script>
</main>