config/routes.rb
Rails.application.routes.draw do  
  devise_for :users, controllers: { registrations: 'users/registrations'}
  root "short_links#home"
  
  # PWA routes
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  
  resources :short_links do
    resource :analytics, only: [:show]
  end
  
  post 'qr_download', to: 'short_links#qr_download', as: :qr_download
  
  get '/about', to: 'static_pages#about', as: 'about'
  get '/terms', to: 'static_pages#terms', as: 'terms_of_service'
  get '/profile', to: 'users#profile', as: 'user_profile'
  post "/", to: 'short_links#home', as: 'short_link_home' 
  get '/:short_link', to: 'short_links#home', as: 'short_link_redirect'
  

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yintii | UrlShortener</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">

    <meta name="google-adsense-account" content="ca-pub-4116671122586959">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :webmanifest) %>
    <%= tag.link rel: "icon", href: "/icon.png", type: "image/png" %>
    <%= tag.link rel: "apple-touch-icon", href: "/icon.png" %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbo-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/chart.js@4.5.1/dist/chart.umd.min.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <!-- rails-ujs via asset pipeline (UMD) so data-method works -->
    <%= javascript_include_tag 'rails-ujs', 'data-turbo-track': 'reload' %>
    <!-- Importmap for Rails/Stimulus -->
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="flash notice" data-controller="flash"><%= flash[:notice] %></div>
    <% end %>
    <% if flash[:alert] %>
      <div class="flash alert" data-controller="flash"><%= flash[:alert] %></div>
    <% end %>
    <% if flash[:success] %>
      <div class="flash success" data-controller="flash"><%= flash[:success] %></div>
    <% end %>
    <% if flash[:error] %>
      <div class="flash error" data-controller="flash"><%= flash[:error] %></div>
    <% end %>

    <header>
      <div id="brand">
        <%= link_to "Yintii", root_path %>
      </div>
      <div id="menu" class="flex flex-end" data-controller="navbar">
        <div id="hamburger-menu" data-action="click->navbar#toggle">
          <span class="hamburger-line"></span>
          <span class="hamburger-line"></span>
          <span class="hamburger-line"></span>
        </div>
        <nav 
          class="hidden flex column"
          data-navbar-target="menu"
          >
          <div id="menu-x" data-action="click->navbar#toggle">
            <span class="x-line"></span>
            <span class="x-line"></span>
          </div>
          
          <%= link_to "Terms of Service", terms_of_service_path %>
          <%= link_to "About", about_path %>
          <% if user_signed_in? %>
            <div class="flex align-center">
              
              <%= link_to user_profile_path, class: "flex align-center" do %>
                <%= gravatar_image_tag(current_user.email, :class => 'gravatar', :alt => 'User Gravatar', :gravatar => { :secure => true } ) %>
                Profile
              <% end %>
            </div>
            <%= link_to "Logout", destroy_user_session_path, method: :delete %>
          <% else %>
            <%= link_to "Login", new_user_session_path %>
            <%= link_to "Sign up", new_user_registration_path %>
          <% end %>
        </nav>
      </div>
    </header>
    <main>
      <div id="main-content">
        <%= yield %>
        <% if current_page?(root_path) && !user_signed_in? %>
          <div class="container flex column align-center p-2 rounded-corners">
            <h2>Want to save your links?</h2>
            <p>Make an account and we'll save your history</p>
            <%= link_to "Sign Up", new_user_registration_path, id: "cta-signup", class: "p-1 rounded-corners"  %>
          </div>
        <% end %>
      </div>
    </main>
  </body>
</html>